# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    api.url: http://pokeapi.co/api/v2/pokemon/

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    api.guzzlehttp:
        class:        GuzzleHttp\Client

    api.manager:
        class:        AppBundle\Api\ApiManager
        arguments:    ['%api.url%', '@api.guzzlehttp']
